services:
  php:
    build:
      context: .
      dockerfile: /docker/Dockerfile
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
